apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      restartPolicy: Always
      containers:
      - name: nginx-app
        image: {{ your_image }}:{{ your_version }}
        ports:
        - name: nginx-http
          containerPort: 80
